[tasks.web_normal]
dependencies = ["clear", "web-wasm-bindgen-cli", "compile_normal", "client"]

[tasks.web_low]
dependencies = ["clear", "web-wasm-bindgen-cli", "compile_low", "client"]


[tasks.compile_normal]
script = '''
cargo build --release --target wasm32-unknown-unknown --features normal --no-default-features
wasm-bindgen --out-name ironverse-editor --out-dir assets/wasm --target web target/wasm32-unknown-unknown/release/ironverse-editor.wasm
'''

[tasks.compile_low]
script = '''
cargo build --release --target wasm32-unknown-unknown --features low --no-default-features
wasm-bindgen --out-name ironverse-editor --out-dir assets/wasm --target web target/wasm32-unknown-unknown/release/ironverse-editor.wasm
'''


[tasks.client]
script = '''
basic-http-server .
'''

[tasks.web-wasm-bindgen-cli]
install_crate = {crate_name = "wasm-bindgen-cli", binary = "wasm-bindgen", test_arg="--help", version="0.2.85"}


[tasks.clear]
script = '''
clear
'''

[tasks.tests]
script = '''
clear
clear
cargo run --features tests --no-default-features
'''

[tasks.normal]
script = '''
clear
clear
cargo run --features normal --no-default-features
'''

[tasks.low]
script = '''
clear
clear
cargo run --features low --no-default-features
'''
