[tasks.web]
dependencies = ["clear", "web-wasm-bindgen-cli", "compile", "client"]

[tasks.web_minimal]
dependencies = ["clear", "web-wasm-bindgen-cli", "compile_minimal", "client"]


[tasks.compile]
script = '''
cargo build --release --target wasm32-unknown-unknown
wasm-bindgen --out-name ironverse-editor --out-dir assets/wasm --target web target/wasm32-unknown-unknown/release/ironverse-editor.wasm
'''

[tasks.compile_minimal]
script = '''
cargo build --release --target wasm32-unknown-unknown --features minimal --no-default-features
wasm-bindgen --out-name ironverse-editor --out-dir assets/wasm --target web target/wasm32-unknown-unknown/release/ironverse-editor.wasm
'''


[tasks.client]
script = '''
basic-http-server .
'''

[tasks.web-wasm-bindgen-cli]
install_crate = {crate_name = "wasm-bindgen-cli", binary = "wasm-bindgen", test_arg="--help", version="0.2.85"}


[tasks.clear]
script = '''
clear
'''

[tasks.run]
script = '''
clear
clear
cargo run
'''

[tasks.run_minimal]
script = '''
clear
clear
cargo run --features minimal --no-default-features
'''